### PR TITLE
Fix nonnull primitive

### PR DESCRIPTION
**Pull request by leonhartX**
The last version which introduced the `usePrimitiveForNonNullField` option has a bug, it will change all  type to primitive if possible. 🙇

### CODE REVIEW

**Review by kainoku — APPROVED** [review]
LGTM

**Comment by seratch** [comment]
Okay. Will ship 0.99.7

**Comment by leonhartX** [comment]
@seratch Thanks!

I've tried to run the release command but got some errors
```
./gradlew clean uploadArchives                                                                             ✔  5253  10:49:53
> Task :signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> Cannot perform signing task ':signArchives' because it has no configured signatory
```

seems I still need to do some prepare work(for the signing key and something else?)

**Comment by seratch** [comment]
You need to set up gpg to work with https://docs.gradle.org/current/userguide/signing_plugin.html

**Comment by seratch** [comment]
It's done. Also, I've pushed the release tag for it.

* https://oss.sonatype.org/content/repositories/staging/com/smartnews/jpa-entity-generator/0.99.7/
* https://oss.sonatype.org/content/repositories/staging/com/smartnews/maven-jpa-entity-generator-plugin/0.99.7/

**Comment by leonhartX** [comment]
Thanks for the quick response! 🙇

**Pull request merged**
