### PR TITLE
Support Jakarta API

### PR DESCRIPTION
**Pull request by weiyuansn**
## Summary
Start from Spring Boot 3, Javax API is replaced by Jakarta API. So adding a `useJakarta` flag to support creating class by using Jakarta API instead of Javax API.

## Detail
Default value of `useJakarta` is `false` in order to not affect current logic.
When `useJakarta=true`, we will use `jakarta.persistence.*`.
If `jsr305AnnotationsRequired=true` is set also, `jakarta.annotation.Nonnull` and `jakarta.annotation.Nullable` are used.

In addition, add a `create_local_database.sh` script for easy setup of `sample-wordpress`.

### CODE REVIEW

**Comment by seratch** [comment]
Hey @weiyuansn, the option should be great for the future but replacing the one for javax annotations can be a breaking change to existing users. Adding the new option to the generator instead should be a more developer-friendly approach. In the real world, many Spring Boot apps will take a certain amount of time for the major version migration.

With that being said, if you are working for SmartNews and the current engineering teams at the company already reached a consensus to drop javax support in future versions of this library to reduce the team's maintenance efforts, I don't oppose to it at all.

**Comment by weiyuansn** [comment]
@seratch Thanks, yes I am working for SmartNews right now and our team is going to upgrade to Spring Boot 3, so I create this PR. Thanks for the advice, let me create an new option for choosing `javax` and `jakarta`.

BTW, after I change to `jakarta` in local and run `./gradlew entityGen` in `sample` folder, nothing happened to those entity class. Did I miss anything? I have been struggled for fail to run `./test.sh` for a while due to test class and entity class didn't update after running `./gradlew entityGen`. 

In addition, for `sample-wordpress`, are there any setup required before running `./gradlew entityGen`? Thanks!

**Comment by seratch** [comment]
I am not sure why the `test.sh` fails now but since the last time I touched this project, there should be many releases on Gradle and its plugins used in this project side. So, you may need to adjust the build settings to be up-to-date.

Since I don't have the bandwidth for this project especially on weekdays, I may not be able to help you out here. This project still supports Java 1.8 but it's about time to drop the support. Some other parts in the build settings can be simpler too.

I am so glad to know the devs at the company are activey working on the Spring Boot major upgrade work. Good luck on the transition!

**Comment by seratch** [comment]
By the way, do you have someone who has the permission to publish jar files onto Sonatype OSS repos / Maven Central for "groupId: com.smartnews"? If not (plus your org still hasn't revoked my permission for it), I am happy to work on the release as necessary.

**Comment by weiyuansn** [comment]
Thanks, I will try to figure out by myself first.

> By the way, do you have someone who has the permission to publish jar files onto Sonatype OSS repos / Maven Central for "groupId: com.smartnews"?

I am not sure right now, let me check it.

**Review by leonhartX — APPROVED** [review]
LGT 🐧 
and thanks @seratch for the advice!!

**Comment by weiyuansn** [comment]
Sorry @leonhartX, do you have permission to merge this PR and release new version? I do not have permission to do that.

**Comment by leonhartX** [comment]
I don't have (lost the permission) either 🤦 , let's ask infra team and corporate

**Comment by weiyuansn** [comment]
@seratch Sorry for mention, this is my first time try to publish to public maven.
When I tried to run followings,
```
./gradlew clean uploadArchives
mvn deploy -Dmaven.test.skip=true
```
`./gradlew clean uploadArchives` reports 
```
> Task :signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchives'.
> Cannot perform signing task ':signArchives' because it has no configured signatory
```

So I think I need to generate and upload a new GPG signature?

Also in gradle task, `SONATYPE_NEXUS_USER` is required, I think I need to get this user from smartnews.

-------

Sorry one more last thing, seems 
```
./gradlew clean uploadArchives
```
```
mvn deploy -Dmaven.test.skip=true
```
are doing same thing, so I can just run either of them? Thanks.

**Comment by seratch** [comment]
@weiyuansn 

>So I think I need to generate and upload a new GPG signature?

Yes, you need to configure GPG and settings for both Gradle and Maven properly. Refer to https://central.sonatype.org/publish/publish-guide/ for details.

>Also in gradle task, SONATYPE_NEXUS_USER is required, I think I need to get this user from smartnews.

If you don't have your Sonatype account yet, you can create a new account and ask their operation team to grant your account to publish jar files under group id: com.smartnews. Probably you can ask this in this thread https://issues.sonatype.org/browse/OSSRH-39113 but if they don't respond to it, you can create a new issue for adding more folks to com.smartnews.

>are doing same thing, so I can just run either of them? Thanks.

This project provides plugins for Gradle and Maven. So, running the two commands is necessary to continue supporting both.

**Pull request merged**
